# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/gui/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(461, 516)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./src/gui/ui\\../../favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTipDuration(1)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.installLocationInput = QtWidgets.QLineEdit(self.centralwidget)
        self.installLocationInput.setGeometry(QtCore.QRect(10, 80, 281, 31))
        self.installLocationInput.setObjectName("installLocationInput")
        self.selectLocationButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectLocationButton.setGeometry(QtCore.QRect(300, 80, 151, 31))
        self.selectLocationButton.setObjectName("selectLocationButton")
        self.projectNameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.projectNameInput.setGeometry(QtCore.QRect(10, 10, 441, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.projectNameInput.setFont(font)
        self.projectNameInput.setStyleSheet("padding: 10px;")
        self.projectNameInput.setObjectName("projectNameInput")
        self.releasedVersionsList = QtWidgets.QListWidget(self.centralwidget)
        self.releasedVersionsList.setGeometry(QtCore.QRect(10, 160, 441, 221))
        self.releasedVersionsList.setObjectName("releasedVersionsList")
        self.selectVersionButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectVersionButton.setGeometry(QtCore.QRect(310, 390, 141, 31))
        self.selectVersionButton.setObjectName("selectVersionButton")
        self.prepareLauncherButton = QtWidgets.QPushButton(self.centralwidget)
        self.prepareLauncherButton.setGeometry(QtCore.QRect(310, 430, 141, 31))
        self.prepareLauncherButton.setObjectName("prepareLauncherButton")
        self.initOnLaunchCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.initOnLaunchCheckBox.setGeometry(QtCore.QRect(10, 390, 251, 20))
        self.initOnLaunchCheckBox.setObjectName("initOnLaunchCheckBox")
        self.selectVersionLabel = QtWidgets.QLabel(self.centralwidget)
        self.selectVersionLabel.setGeometry(QtCore.QRect(10, 120, 441, 31))
        self.selectVersionLabel.setObjectName("selectVersionLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 461, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PHP Launchpad v1.3.0"))
        self.selectLocationButton.setText(_translate("MainWindow", "Browse Location"))
        self.projectNameInput.setPlaceholderText(_translate("MainWindow", "Name of the project"))
        self.selectVersionButton.setText(_translate("MainWindow", "Select Version"))
        self.prepareLauncherButton.setText(_translate("MainWindow", "Setup Launcher"))
        self.initOnLaunchCheckBox.setText(_translate("MainWindow", "Initialize project quitly on installation?"))
        self.selectVersionLabel.setText(_translate("MainWindow", "Select the version you want to setup from below"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
